### ISSUE TITLE
Create a pull request

### ISSUE THREAD

**Issue by dasJ** [stuvusIT/nextcloud#1]

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 88 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 96 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 138 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 157 days.

**Comment by Scriptkiddi** [comment]
2018-01-31 release date for nc 13 https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
